# Generated by Django 5.0.6 on 2024-05-15 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='текст')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='изображение')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='текст')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='публикация')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ['-date_posted'],
            },
        ),
    ]
