# Generated by Django 5.0.6 on 2024-05-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_edition',
            field=models.DateTimeField(auto_now=True, verbose_name='дата редактирования'),
        ),
    ]
